language: scala

# only trigger builds on master
branches:
  only:
    - master
    - v3.1.x

before_script:
  - sudo chmod +x /usr/local/bin/sbt

script:
  - sbt clean coverage test coverageReport coverageAggregate codacyCoverage

scala:
   - 2.11.12
   - 2.12.8
   - 2.13.0-M5

before_install:
    - pip install --user codecov

after_success:
  - codecov

jdk:
  - openjdk8
